export const memories = [
  { image: "public/Snapchat-1965516301.jpg", description: "The time we used to meet hiding from everyone, where everything was a secret" },
  { image: "public/Screenshot_2024-01-05-17-33-23-87_a63b0f8076346d26cbdc1b971a1da2a7.jpg", description: "First time you proposed me, although it was on text, but it was special to me" },
  { image: "public/Snapchat-2011255041.jpg", description: "Can't forget this day, first time you sat on my lap in front of your bitch friend (you know who)" },
  { image: "public/IMG-20240622-WA0008.jpg", description: "How you used to assault me with your hickeys" },
  { image: "public/Screenshot_2026-01-30-22-58-27-97_6012fa4d4ddec268fc5c7112cbb265e7.jpg", description: "Your first birthday that we celebrated two years ago, you looked so gorgeous that day" },
  { image: "public/IMG20240119193611.jpg", description: "How we used to walk till night in front of H15" },
  { image: "public/IMG_20260130_223612.jpg", description: "Our first valentine's day together, couldn't take my eyes off you that day" },
  { image: "public/IMG-20250504-WA0012.jpg", description: "Remember? How you almost didn't attend and I pushed, you look so beautiful in saree" },
  { image: "public/Snapchat-1693745654.jpg", description: "initial days at H9, how you got addicted to hugging me while sleeping" },
  { image: "public/Snapchat-578212717.jpg", description: "Our first diwali together, we really celebrated it like a married couple" },
  { image: "public/Snapchat-15278200.jpg", description: "My last official day in insti, and I got to spend it with you, so grateful <3" },
  { image: "public/IMG-20250131-WA0002.jpg", description: "I miss doing things on your birthday for you" },
  { image: "public/Snapchat-375357045.jpg", description: "the day we went to isckon first time together, although i am atheist but i prayed for us" },
  { image: "public/IMG20240118113107.jpg", description: "how i used to attend your classes just to be near you at the start of our affair" },
  { image: "public/IMG-20250315-WA0005.jpg", description: "the holi we really enjoyed as a couple, really into each other" },
  { image: "public/Snapchat-1228181344.jpg", description: "how you took an ENT course just because of me, just to be near me XD" },
  { image: "public/IMG-20240905-WA0031.jpg", description: "Our first salsa night together <3, you really looked like a doll" },
  { image: "public/Snapchat-568317745.jpg", description: "first time i went to drop you at station, you started crying when train started leaving" },
  { image: "public/IMG-20250208-WA0045.jpg", description: "our first mood indigo as a couple, you looked so hot that i wanted to just ... (can't say it here)" },
  { image: "public/IMG-20240127-WA0007.jpg", description: "your childish acts like this, only goes to prove you're the cutest in the world" },
  { image: "public/Snapchat-1692435441.jpg", description: "cannot put an image for the exact memory, will go with this, our crazy love making and s*x at H11" },
  { image: "public/IMG20251227134950.jpg", description: "our first trip together, though it had ups and downs, but it was beautiful, cuz you were in it" },
  { image: "public/IMG-20250414-WA0015.jpg", description: "our first prom night, and this picture tells it all, how much we love each other" },
  { image: "public/IMG_4853.JPG", description: "my most fav memory of you, how we pronounced our love to the world" }
];

export const reasons = [
  { image: "public/Snapchat-1688066029.jpg", description: "you bring out the inner child in me, the child that was once dead, you respawned it <3" },
  { image: "public/IMG20240203165252.jpg", description: "how you hug me like i am your everything in the world" },
  { image: "public/Snapchat-1394412124.jpg", description: "just one word - GUPPA, major reason I fell for you (after your ***** ofc)" },
  { image: "public/Snapchat-2000653455.jpg", description: "how you support me in every way possible to see my thrive" },
  { image: "public/Snapchat-615928038.jpg", description: "how you try to look as beautiful for me as possible, though you are the most beautiful in my eyes" },
  { image: "public/Snapchat-689200893.jpg", description: "how you care about each and every part of me, my health, my career, my family, everything" },
  { image: "public/Snapchat-1369349818.jpg", description: "how your heart and mind is so pure, not even" },
  { image: "public/Screenshot_2026-01-30-23-01-20-66_a63b0f8076346d26cbdc1b971a1da2a7.jpg", description: "how you teach me not take myself so seriously" },
  { image: "public/IMG-20240109-WA0001.jpg", description: "self explanatory, you're just so hotttttt" },
  { image: "public/Snapchat-1921206436.jpg", description: "the way you become a child in front of me" },
  { image: "public/Snapchat-1016177217.jpg", description: "how you never leave my side, no matter what the situation is" },
  { image: "public/Screenshot_2026-01-30-23-02-00-70_a63b0f8076346d26cbdc1b971a1da2a7.jpg", description: "you're one of the strongest women i know of, you inspire me a lot" },
  { image: "public/IMG20241118163540.jpg", description: "i am always the topmost priority for me, you'd burn the world for me really" },
  { image: "public/Snapchat-956550397.jpg", description: "how you listen to each and every rant of mine, doesn't matter how senseless it is" },
  { image: "public/Snapchat-453479636.jpg", description: "how you are ready to fight every battle with me, for me" },
  { image: "public/Snapchat-2164748.jpg", description: "How you’ve become my safe place and my home." },
  { image: "public/Snapchat-349736243.jpg", description: "Your smile—it’s literally infectious." },
  { image: "public/IMG-20251230-WA0005.jpg", description: "how you chose me at my worst, even when everyone around you was telling you not to" },
  { image: "public/Snapchat-1626349010.jpg", description: "how you push me everytime i start to lose motivation" },
  { image: "public/Snapchat-1919326476.jpg", description: "how you have always believed in me, even when i am failing" },
  { image: "public/IMG-20250208-WA0045.jpg", description: "when i am around you, holding you, i am the happiest man alive" },
  { image: "public/IMG20240214222808.jpg", description: "how you are so small and have a baby like face, makes me feel so huge" },
  { image: "public/IMG20251227134950.jpg", description: "how you risk things, just to make me happy and satisfied" },
  { image: "public/IMG20240119193611.jpg", description: "Because you are simply my favorite human." }
];

export const future = [
  { image: "public/Screenshot 2026-01-31 at 12.32.28 AM.png", description: "living together comes very first, can't wait anymore now );" },
  { image: "public/Screenshot 2026-01-31 at 12.33.39 AM.png", description: "waking up next to you every morning, without our clothes on" },
  { image: "public/Screenshot 2026-01-31 at 12.34.17 AM.png", description: "cooking food for you, taking care of you like a baby when we live together" },
  { image: "public/Screenshot 2026-01-31 at 12.34.40 AM.png", description: "traveling the whole world with you" },
  { image: "public/Screenshot 2026-01-31 at 12.35.03 AM.png", description: "making love in each and every part of the world" },
  { image: "public/Screenshot 2026-01-31 at 12.35.35 AM.png", description: "long bike rides with you, just you" },
  { image: "public/Screenshot 2026-01-31 at 12.36.36 AM.png", description: "walking hand in hand in front of everyone who thought we wouldn't work" },
  { image: "public/Screenshot 2026-01-31 at 12.37.06 AM.png", description: "watching a sunset where we don't have to say goodbye" },
  { image: "public/Screenshot 2026-01-31 at 12.37.36 AM.png", description: "making a lot of money together and buying us a big house" },
  { image: "public/Screenshot 2026-01-31 at 12.37.58 AM.png", description: "grinding with you, and succeeding with you, being a power couple" },
  { image: "public/Screenshot 2026-01-31 at 12.38.44 AM.png", description: "learning new things together, and failing at all of them XD" },
  { image: "public/Screenshot 2026-01-31 at 12.39.14 AM.png", description: "do daily exercises with you, so i can see your glutes and chest move in waves" },
  { image: "public/Screenshot 2026-01-31 at 12.39.58 AM.png", description: "Supporting each other through new career milestones." },
  { image: "public/Screenshot 2026-01-31 at 12.40.37 AM.png", description: "doing anything that makes us happy, even if it doesn't make sense to others" },
  { image: "public/Screenshot 2026-01-31 at 12.41.24 AM.png", description: "introducing each other to our families, not as friends, but as lovers" },
  { image: "public/Screenshot 2026-01-31 at 12.42.05 AM.png", description: "travel and eat everywhere in the world, whatever's their special dish" },
  { image: "public/Screenshot 2026-01-31 at 12.42.47 AM.png", description: "making crazyyy love to you everyday" },
  { image: "public/IMG-20250131-WA0002.jpg", description: "Celebrating every birthday together in person." },
  { image: "public/Screenshot 2026-01-31 at 12.44.01 AM.png", description: "kissing each other everyday, at least a million times per day" },
  { image: "public/Screenshot 2026-01-31 at 12.45.02 AM.png", description: "proposing to you for our marriage in the best way possible" },
  { image: "public/Screenshot 2026-01-31 at 12.45.39 AM.png", description: "planning our wedding together" },
  { image: "public/Screenshot 2026-01-31 at 12.46.01 AM.png", description: "calling you my wife, proudly in front of the world" },
  { image: "public/Screenshot 2026-01-31 at 12.46.31 AM.png", description: "having like a dozen kids XD, and still be more lively then all of them" },
  { image: "public/Screenshot 2026-01-31 at 12.47.14 AM.png", description: "growing old and grey with you by my side." }
];